export const categories = ["World", "Nation", "Business", "Technology", "Entertainment", "Sports", "Science", "Health"]

export const languages = [
  { name: "Arabic", lang: "ar" },
  { name: "Chinese", lang: "zh" },
  { name: "Dutch", lang: "nl" },
  { name: "English", lang: "en" },
  { name: "French", lang: "fr" },
  { name: "German", lang: "de" },
  { name: "Greek", lang: "el" },
  { name: "Hebrew", lang: "he" },
  { name: "Hindi", lang: "hi" },
  { name: "Italian", lang: "it" },
  { name: "Japanese", lang: "ja" },
  { name: "Malayalam", lang: "ml" },
  { name: "Marathi", lang: "mr" },
  { name: "Norwegian", lang: "no" },
  { name: "Portuguese", lang: "pt" },
  { name: "Romanian", lang: "ro" },
  { name: "Russian", lang: "ru" },
  { name: "Spanish", lang: "es" },
  { name: "Swedish", lang: "sv" },
  { name: "Tamil", lang: "ta" },
  { name: "Telugu", lang: "te" },
  { name: "Ukrainian", lang: "uk" }
];

export const countries = [
  { name: "Australia", code: "au" },
  { name: "Brazil", code: "br" },
  { name: "Canada", code: "ca" },
  { name: "China", code: "cn" },
  { name: "Egypt", code: "eg" },
  { name: "France", code: "fr" },
  { name: "Germany", code: "de" },
  { name: "Greece", code: "gr" },
  { name: "Hong Kong", code: "hk" },
  { name: "India", code: "in" },
  { name: "Ireland", code: "ie" },
  { name: "Israel", code: "il" },
  { name: "Italy", code: "it" },
  { name: "Japan", code: "jp" },
  { name: "Netherlands", code: "nl" },
  { name: "Norway", code: "no" },
  { name: "Pakistan", code: "pk" },
  { name: "Peru", code: "pe" },
  { name: "Philippines", code: "ph" },
  { name: "Portugal", code: "pt" },
  { name: "Romania", code: "ro" },
  { name: "Russian Federation", code: "ru" },
  { name: "Singapore", code: "sg" },
  { name: "Spain", code: "es" },
  { name: "Sweden", code: "se" },
  { name: "Switzerland", code: "ch" },
  { name: "Taiwan", code: "tw" },
  { name: "Ukraine", code: "ua" },
  { name: "United Kingdom", code: "gb" },
  { name: "United States", code: "us" }
];